"""
Django settings for HackerNews project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path

# Configura el backend de almacenamiento predeterminado para S3
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

# Configuración de S3
AWS_ACCESS_KEY_ID = "ASIAQ2NVUYZ5722OYSQR"
AWS_SECRET_ACCESS_KEY = "TKygBhze/eGvTMOYmSfSrZqBgOmTDbAmqJUcN7Gu"
AWS_SESSION_TOKEN = "IQoJb3JpZ2luX2VjEFEaCXVzLXdlc3QtMiJHMEUCIQCMYDrfAnzarTRi2jUxrkkT/mnJmLweKR7paM0fQKJrvgIgSFtTGFemBmIPZL0lK3adT9jQOKtC0hGbe4lqVnP3s6UqxAII2v//////////ARAAGgwwNTY3NTIzOTE4MDMiDL5C3QKCjFgzQCbbLCqYAkchPk5Q8o2LrllISjBUR4E3ZNTEZ59WwFNlKMgh0Wn6gCrSEZXKxeOAMFK+GLxb7AbWaQNn93GYyHT4NRMDG43R8NdY5c83QwHzQpv8UaXkzDuWcg0kFr29B0IKe/WzjOni8f3Iu1hXI06nki+/2YjfEpt2jzEHO4lz5gp9AAvlK8A1tLk+gvPqR4M/DkUQZBBOhqFtT8Tfc3GGGhnhqIsu6FKMwJUuSwTJ8NUZBGPfWgw/oucf6NNZijvqmJFkgZtcVJ2HY1hQUYY8C5SJWgGiNngnwN3fo38cnM09VrghiMiOSgjv+ah905xgp5YXl04S/Vm0FBOZzWnFH3Kjavdv3qLRA0O9NV6yn8lY9/l99HaetCysiSUwmbvTuQY6nQFQZDanGMuqyXo1ONc/DsLeR/uy670FcwqU5duFOYF/BZXZs7n00lthvIKi3nTUpco4VKbVSCA07fU0I8Znw38sx0pRLRdcfjyBXWWwIvy4cIuiLffTm/cwsPoz3aiUXHN/doSavckLiIY9pPw7hs3CkVKYw0ReRgZNP5PD8uks75Ok/LaV1lJHubaeIzdCrQu9sFQRxoYwlIEuy4ut"
AWS_STORAGE_BUCKET_NAME = 'labasw'
AWS_S3_REGION_NAME = 'us-east-1'  # Cambia a tu región de S3
AWS_QUERYSTRING_AUTH = False  # Para deshabilitar las firmas de URL en archivos públicos

# Opcional: para que los archivos cargados sean públicos por defecto
AWS_DEFAULT_ACL = 'public-read'

# Opcional: configurar la URL base de los archivos cargados
AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com'
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/'


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ke=1-=z93(bu_4gf7fzf98&dhn%d04m8dut!41$f3n^u%@id#h'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'https://0256-84-78-248-85.ngrok-free.app']
SITE_ID = 1


# Application definition

INSTALLED_APPS = [
    'storages',
    'News',
    'django.contrib.sites',
    'social_django',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

AUTHENTICATION_BACKENDS = (
    'social_core.backends.google.GoogleOAuth2',  # for Google
    'django.contrib.auth.backends.ModelBackend',  # to use Django's built-in user auth
)



MIDDLEWARE = [
    'social_django.middleware.SocialAuthExceptionMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Google OAuth keys from the Google Developer Console
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = '971326311730-3nv4n4d8gm5i8jlbt2jqof9n08gqvmgc.apps.googleusercontent.com'
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = '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'

# Set login and logout URLs
LOGIN_URL = 'login'
LOGOUT_URL = 'logout'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# Add Social Auth pipeline to create a user if it doesn't exist
SOCIAL_AUTH_PIPELINE = (
    'social_core.pipeline.social_auth.social_details',
    'social_core.pipeline.social_auth.social_uid',
    'social_core.pipeline.social_auth.auth_allowed',
    'social_core.pipeline.social_auth.social_user',
    'social_core.pipeline.user.get_username',
    'social_core.pipeline.user.create_user',
    'social_core.pipeline.social_auth.associate_user',
    'social_core.pipeline.social_auth.load_extra_data',
    'News.pipeline.create_user_profile',
    'social_core.pipeline.user.user_details',
)

# Store social auth data in the session
SOCIAL_AUTH_SESSION_EXPIRATION = False

# URL used to complete authentication
SOCIAL_AUTH_URL_NAMESPACE = 'social'

ROOT_URLCONF = 'HackerNews.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'HackerNews.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / "News/static",  
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
