# Generated by Django 5.1.2 on 2024-11-08 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0008_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='submissions', to='News.comment'),
        ),
    ]
