# Generated by Django 5.1.2 on 2024-11-07 16:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0008_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='voters',
            field=models.ManyToManyField(blank=True, related_name='voted_submissions', to=settings.AUTH_USER_MODEL),
        ),
    ]
