# Generated by Django 5.1.2 on 2024-11-07 17:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0009_submission_voters'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='hidden_by',
            field=models.ManyToManyField(blank=True, related_name='hidden_submissions', to=settings.AUTH_USER_MODEL),
        ),
    ]
