# Generated by Django 5.1.2 on 2024-11-12 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0011_submission_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='content',
        ),
    ]
