# Generated by Django 5.1.2 on 2024-11-12 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0010_submission_hidden_by'),
        ('News', '0013_rename_content_comment_text'),
    ]

    operations = [
    ]
