# Generated by Django 5.1.2 on 2024-11-12 16:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0014_merge_20241112_1727'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorited_submissions', to=settings.AUTH_USER_MODEL),
        ),
    ]
