# Generated by Django 5.1.2 on 2024-11-12 16:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0015_submission_favorited_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorited_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
