# Generated by Django 5.1.2 on 2024-11-13 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0009_alter_userprofile_avatar_alter_userprofile_banner'),
        ('News', '0018_alter_comment_author'),
    ]

    operations = [
    ]
