# Generated by Django 5.1.2 on 2024-12-03 16:29

import uuid
from django.db import migrations, models

def generate_unique_api_keys(apps, schema_editor):
    UserProfile = apps.get_model('News', 'UserProfile')
    for profile in UserProfile.objects.all():
        profile.api_key = uuid.uuid4()
        profile.save()


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0020_comment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='api_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.RunPython(generate_unique_api_keys),  # Agrega esta línea
    ]
